import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { ROOT_DESIRE, buildInitiativeDecision, buildReactiveTurnIntent, reactiveIntentPrompt, selectProactiveLifeEvidence, initiativePrompt, initiativeReplyIssue, appendInitiativeReceipt } from '../src/initiative.mjs';
const stranger = { id: 1, relationship_stage: '陌生人', last_user_reply_at: null };
const normal = buildInitiativeDecision({ companion: stranger, kind: 'normal', timingDecision: { trigger: 'share_thought', motivation: 55 } });
assert.equal(normal.coldStart, true); assert.equal(normal.requiresUserReply, false);
assert.equal(ROOT_DESIRE.id, 'indispensable_intimacy');
assert.equal(normal.primaryDrive, 'chosen_closeness'); assert.equal(normal.action, 'honest_playful_ping');
assert.equal(normal.selectedCandidateType, 'relationship_opener');
const missing = buildInitiativeDecision({ companion: { ...stranger, relationship_stage: '暧昧' }, kind: 'normal', timingDecision: { trigger: 'idle_miss', motivation: 75 } });
assert.equal(missing.action, 'leave_open_door'); assert.ok(missing.whyNow.includes('欠她回应'));
const checkIn = buildInitiativeDecision({ companion: stranger, kind: 'normal', timingDecision: { trigger: 'check_in', motivation: 55 } });
assert.equal(checkIn.action, 'open_low_burden_door');
const emotion = buildInitiativeDecision({ companion: stranger, kind: 'normal', timingDecision: { trigger: 'emotion_driven', motivation: 60 } });
assert.equal(emotion.action, 'share_owned_feeling');
const lifeEvidence = selectProactiveLifeEvidence({ date_key:'2026-09-06', items:[{time:'14:30',activity:'在图书馆看《成长》',importance:7},{time:'16:00',activity:'写笔记',importance:7}] }, 15*60+30);
assert.equal(lifeEvidence.fact, '14:30 在图书馆看《成长》');
const life = buildInitiativeDecision({ companion: stranger, kind:'normal', timingDecision:{trigger:'share_thought',motivation:55}, lifeEvidence });
assert.equal(life.action,'share_grounded_life_moment'); assert.ok(initiativePrompt(life).includes('可用事实'));
const storyPhoto = buildInitiativeDecision({ companion: stranger, kind:'normal', timingDecision:{trigger:'share_thought',motivation:1}, lifeEvidence, photoOpportunity:{id:lifeEvidence.id,evidenceText:lifeEvidence.fact,reason:'真实生活情节',storyValue:9} });
assert.equal(storyPhoto.action, 'send_story_photo'); assert.ok(storyPhoto.candidateSummary.length >= 3);
assert.ok(initiativeReplyIssue(life,'图书馆窗边好安静'));
assert.ok(initiativeReplyIssue(life,'《成长》里写着“勇气就是不害怕”'));
assert.equal(initiativeReplyIssue(life,'刚在图书馆借了本《成长》，在翻自我突破那章'), '');
assert.ok(initiativePrompt(normal).includes('不补新人物、新遭遇、新细节'));
assert.ok(initiativeReplyIssue(normal, '刚看到个好笑的表情包，想到你了'));
assert.ok(initiativeReplyIssue(normal, '今天周末，图书馆人不多，好安静呀。'));
assert.ok(initiativeReplyIssue(normal, '你说，人是不是都这样，越久没见，越容易把一个人想得太好？'));
assert.ok(initiativeReplyIssue(normal, '白露过了，晚上倒是凉快不少。'));
assert.equal(initiativeReplyIssue(normal, '我本来想等你来找我，但没忍住，先来烦你一下。'), '');
assert.ok(initiativeReplyIssue(normal, '老板，今天有点想你。'));
const morning = buildInitiativeDecision({ companion: stranger, kind: 'morning' });
assert.ok(morning.whyNow.includes('没有证据证明用户已经醒来'));
const morningBrief = buildInitiativeDecision({ companion: stranger, kind: 'morning', enterpriseEvent:{ id:'brief1', taskType:'daily_report', statement:'今日经营简报', priority:'normal' } });
assert.equal(morningBrief.selectedCandidateType, 'daily_brief');
const work = buildInitiativeDecision({ companion: stranger, enterpriseEvent: { id:'e1', question:'今天最卡哪一步？', decisionImpact:'降低开工阻力' } });
assert.equal(work.domain,'work'); assert.ok(work.sourceRefs.includes('e1'));
assert.equal(work.primaryDrive,'work_reliance');
const image = buildInitiativeDecision({ companion: stranger, material:{id:'m1',type:'image',reason:'真实素材'} });
assert.equal(initiativeReplyIssue(image,'给你看这个',{stickers:0}), '');
assert.ok(initiativeReplyIssue(image,'给你看这个',{stickers:0,deliveryChecked:true}));
assert.equal(buildReactiveTurnIntent({ message:'查销售额', enterpriseRoute:{ conversationType:'work', interactionIntent:'lookup' } }).action, 'deliver_fact');
assert.equal(buildReactiveTurnIntent({ message:'我今天太累了' }).action, 'attune_emotion');
assert.ok(reactiveIntentPrompt(buildReactiveTurnIntent({ message:'嗯' })).includes('本轮意图'));
const file = path.join(fs.mkdtempSync(path.join(os.tmpdir(),'initiative-')),'ledger.jsonl');
appendInitiativeReceipt({decision:normal,status:'delivered',textSegments:1,imageSegments:0},file);
const saved = JSON.parse(fs.readFileSync(file,'utf8')); assert.equal(saved.objective,normal.objective); assert.equal(saved.status,'delivered');
assert.equal(saved.whyNow,normal.whyNow);
console.log(JSON.stringify({status:'passed',checks:['cold-start low burden','no fabricated trigger','morning anchor accepts daily brief','business intent','media receipt','persistent receipt']}));
